# Generated by Django 4.0 on 2021-12-19 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FlightApp', '0002_alter_flight_arrival_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date0f_departure',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 19), null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimated_time_of_departure',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 12, 19, 7, 28, 8, 365368, tzinfo=utc)),
        ),
    ]
