# Generated by Django 4.0 on 2021-12-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightApp', '0004_alter_flight_date0f_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date0f_departure',
            field=models.DateField(blank=True, default='2021-12-20', null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimated_time_of_departure',
            field=models.TimeField(blank=True, default='08:05'),
        ),
    ]
