# Generated by Django 4.0 on 2021-12-20 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlightApp', '0005_alter_flight_date0f_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='estimated_time_of_departure',
            field=models.TimeField(blank=True, default='14:12:13'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightApp.passenger'),
        ),
    ]
